program T2TiERPContratos;

uses
  Forms,
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  ColaboradorController in '..\Comum\Controller\ColaboradorController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  Tipos in '..\Comum\Tipos.pas',
  UMenu in 'Tela\UMenu.pas' {FMenu},
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  UContratoTipoServico in 'Tela\UContratoTipoServico.pas' {FContratoTipoServico},
  ContratoTipoServicoController in 'Controller\ContratoTipoServicoController.pas',
  ContratoTipoServicoVO in '..\..\Comum\VO\ContratoTipoServicoVO.pas',
  TipoContratoController in 'Controller\TipoContratoController.pas',
  TipoContratoVO in '..\..\Comum\VO\TipoContratoVO.pas',
  UTipoContrato in 'Tela\UTipoContrato.pas' {FTipoContrato},
  UContratoSolicitacaoServico in 'Tela\UContratoSolicitacaoServico.pas' {FContratoSolicitacaoServico},
  ContratoSolicitacaoServicoController in 'Controller\ContratoSolicitacaoServicoController.pas',
  ContratoSolicitacaoServicoVO in '..\..\Comum\VO\ContratoSolicitacaoServicoVO.pas',
  ClienteController in 'Controller\ClienteController.pas',
  ClienteVO in '..\..\Comum\VO\ClienteVO.pas',
  FornecedorController in 'Controller\FornecedorController.pas',
  SetorController in 'Controller\SetorController.pas',
  FornecedorVO in '..\..\Comum\VO\FornecedorVO.pas',
  UContrato in 'Tela\UContrato.pas' {FContrato},
  ContratoController in 'Controller\ContratoController.pas',
  ContratoHistFaturamentoVO in '..\..\Comum\VO\ContratoHistFaturamentoVO.pas',
  ContratoHistoricoReajusteVO in '..\..\Comum\VO\ContratoHistoricoReajusteVO.pas',
  ContratoPrevFaturamentoVO in '..\..\Comum\VO\ContratoPrevFaturamentoVO.pas',
  ContratoVO in '..\..\Comum\VO\ContratoVO.pas',
  ContabilContaController in 'Controller\ContabilContaController.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  FornecedorPessoaVO in '..\..\Comum\VO\FornecedorPessoaVO.pas',
  ClientePessoaVO in '..\..\Comum\VO\ClientePessoaVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  ContratoTemplateController in 'Controller\ContratoTemplateController.pas',
  ContratoTemplateVO in '..\..\Comum\VO\ContratoTemplateVO.pas',
  UContratoTemplate in 'Tela\UContratoTemplate.pas' {FContratoTemplate},
  UDocumentoWord in 'Tela\UDocumentoWord.pas' {FDocumentoWord},
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ViewContratoDadosContratanteVO in '..\..\Comum\VO\ViewContratoDadosContratanteVO.pas',
  ViewContratoDadosContratanteController in 'Controller\ViewContratoDadosContratanteController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Gestão de Contratos';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
