program T2TiERPPontoEletronico;

uses
  Forms,
  Constantes in '..\..\Comum\Constantes.pas',
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  ColaboradorController in '..\Comum\Controller\ColaboradorController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  UPontoParametro in 'Tela\UPontoParametro.pas' {FPontoParametro},
  PontoParametroController in 'Controller\PontoParametroController.pas',
  PontoParametroVO in '..\..\Comum\VO\PontoParametroVO.pas',
  PontoHorarioController in 'Controller\PontoHorarioController.pas',
  PontoHorarioVO in '..\..\Comum\VO\PontoHorarioVO.pas',
  UPontoHorario in 'Tela\UPontoHorario.pas' {FPontoHorario},
  PontoRelogioVO in '..\..\Comum\VO\PontoRelogioVO.pas',
  PontoRelogioController in 'Controller\PontoRelogioController.pas',
  UPontoRelogio in 'Tela\UPontoRelogio.pas' {FPontoRelogio},
  PontoAbonoController in 'Controller\PontoAbonoController.pas',
  PontoAbonoUtilizacaoVO in '..\..\Comum\VO\PontoAbonoUtilizacaoVO.pas',
  PontoAbonoVO in '..\..\Comum\VO\PontoAbonoVO.pas',
  UPontoAbono in 'Tela\UPontoAbono.pas' {FPontoAbono},
  PontoEscalaController in 'Controller\PontoEscalaController.pas',
  PontoEscalaVO in '..\..\Comum\VO\PontoEscalaVO.pas',
  PontoTurmaVO in '..\..\Comum\VO\PontoTurmaVO.pas',
  UPontoEscala in 'Tela\UPontoEscala.pas' {FPontoEscala},
  PontoTurmaController in 'Controller\PontoTurmaController.pas',
  UPontoBancoHoras in 'Tela\UPontoBancoHoras.pas' {FPontoBancoHoras},
  PontoBancoHorasController in 'Controller\PontoBancoHorasController.pas',
  PontoBancoHorasVO in '..\..\Comum\VO\PontoBancoHorasVO.pas',
  PontoHorarioAutorizadoController in 'Controller\PontoHorarioAutorizadoController.pas',
  PontoHorarioAutorizadoVO in '..\..\Comum\VO\PontoHorarioAutorizadoVO.pas',
  UPontoHorarioAutorizado in 'Tela\UPontoHorarioAutorizado.pas' {FPontoHorarioAutorizado},
  PontoMarcacaoController in 'Controller\PontoMarcacaoController.pas',
  PontoMarcacaoVO in '..\..\Comum\VO\PontoMarcacaoVO.pas',
  UPontoGeracaoArquivos in 'Tela\UPontoGeracaoArquivos.pas' {FPontoGeracaoArquivos},
  UPontoEspelho in 'Tela\UPontoEspelho.pas' {FPontoEspelho},
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  PontoBancoHorasUtilizacaoVO in '..\..\Comum\VO\PontoBancoHorasUtilizacaoVO.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  UPontoClassificacaoJornada in 'Tela\UPontoClassificacaoJornada.pas' {FPontoClassificacaoJornada},
  PontoClassificacaoJornadaController in 'Controller\PontoClassificacaoJornadaController.pas',
  PontoClassificacaoJornadaVO in '..\..\Comum\VO\PontoClassificacaoJornadaVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  ViewColaboradorPisController in '..\Comum\Controller\ViewColaboradorPisController.pas',
  ViewColaboradorPisVO in '..\..\Comum\VO\ViewColaboradorPisVO.pas',
  UPontoRegistroIncluidoAFD in 'Tela\UPontoRegistroIncluidoAFD.pas' {FPontoRegistroIncluidoAFD},
  UPontoTratamentoArquivoAFD in 'Tela\UPontoTratamentoArquivoAFD.pas' {FPontoTratamentoArquivoAFD},
  ViewPontoMarcacaoController in 'Controller\ViewPontoMarcacaoController.pas',
  ViewPontoMarcacaoVO in '..\..\Comum\VO\ViewPontoMarcacaoVO.pas',
  ViewPontoEscalaTurmaController in 'Controller\ViewPontoEscalaTurmaController.pas',
  ViewPontoEscalaTurmaVO in '..\..\Comum\VO\ViewPontoEscalaTurmaVO.pas',
  PontoFechamentoJornadaController in 'Controller\PontoFechamentoJornadaController.pas',
  PontoFechamentoJornadaVO in '..\..\Comum\VO\PontoFechamentoJornadaVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Ponto Eletrônico';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
