program T2TiERPFolha;

uses
  Forms,
  Windows,
  Dialogs,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  AlmoxarifadoVO in '..\..\Comum\VO\AlmoxarifadoVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  ClienteVO in '..\..\Comum\VO\ClienteVO.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  ContaCaixaVO in '..\..\Comum\VO\ContaCaixaVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  MunicipioVO in '..\..\Comum\VO\MunicipioVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  SalarioMinimoVO in '..\..\Comum\VO\SalarioMinimoVO.pas',
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  BancoVO in '..\..\Comum\VO\BancoVO.pas',
  AgenciaBancoVO in '..\..\Comum\VO\AgenciaBancoVO.pas',
  FolhaParametrosController in 'Controller\FolhaParametrosController.pas',
  GuiasAcumuladasVO in '..\..\Comum\VO\GuiasAcumuladasVO.pas',
  FeriasPeriodoAquisitivoVO in '..\..\Comum\VO\FeriasPeriodoAquisitivoVO.pas',
  FolhaAfastamentoVO in '..\..\Comum\VO\FolhaAfastamentoVO.pas',
  FolhaEventoVO in '..\..\Comum\VO\FolhaEventoVO.pas',
  FolhaFechamentoVO in '..\..\Comum\VO\FolhaFechamentoVO.pas',
  FolhaFeriasColetivasVO in '..\..\Comum\VO\FolhaFeriasColetivasVO.pas',
  FolhaHistoricoSalarialVO in '..\..\Comum\VO\FolhaHistoricoSalarialVO.pas',
  FolhaInssRetencaoVO in '..\..\Comum\VO\FolhaInssRetencaoVO.pas',
  FolhaInssServicoVO in '..\..\Comum\VO\FolhaInssServicoVO.pas',
  FolhaInssVO in '..\..\Comum\VO\FolhaInssVO.pas',
  FolhaLancamentoCabecalhoVO in '..\..\Comum\VO\FolhaLancamentoCabecalhoVO.pas',
  FolhaLancamentoDetalheVO in '..\..\Comum\VO\FolhaLancamentoDetalheVO.pas',
  FolhaParametrosVO in '..\..\Comum\VO\FolhaParametrosVO.pas',
  FolhaPppAtividadeVO in '..\..\Comum\VO\FolhaPppAtividadeVO.pas',
  FolhaPppCatVO in '..\..\Comum\VO\FolhaPppCatVO.pas',
  FolhaPppExameMedicoVO in '..\..\Comum\VO\FolhaPppExameMedicoVO.pas',
  FolhaPppFatorRiscoVO in '..\..\Comum\VO\FolhaPppFatorRiscoVO.pas',
  FolhaPppVO in '..\..\Comum\VO\FolhaPppVO.pas',
  FolhaRescisaoVO in '..\..\Comum\VO\FolhaRescisaoVO.pas',
  FolhaTipoAfastamentoVO in '..\..\Comum\VO\FolhaTipoAfastamentoVO.pas',
  FolhaValeTransporteVO in '..\..\Comum\VO\FolhaValeTransporteVO.pas',
  UFolhaParametros in 'Tela\UFolhaParametros.pas' {FFolhaParametros},
  UGuiasAcumuladas in 'Tela\UGuiasAcumuladas.pas' {FGuiasAcumuladas},
  GuiasAcumuladasController in 'Controller\GuiasAcumuladasController.pas',
  UFolhaPlanoSaude in 'Tela\UFolhaPlanoSaude.pas' {FFolhaPlanoSaude},
  FolhaPlanoSaudeController in 'Controller\FolhaPlanoSaudeController.pas',
  FolhaPlanoSaudeVO in '..\..\Comum\VO\FolhaPlanoSaudeVO.pas',
  FolhaEventoController in 'Controller\FolhaEventoController.pas',
  UFolhaEvento in 'Tela\UFolhaEvento.pas' {FFolhaEvento},
  UFolhaTipoAfastamento in 'Tela\UFolhaTipoAfastamento.pas' {FFolhaTipoAfastamento},
  FolhaTipoAfastamentoController in 'Controller\FolhaTipoAfastamentoController.pas',
  FolhaAfastamentoController in 'Controller\FolhaAfastamentoController.pas',
  UFolhaAfastamento in 'Tela\UFolhaAfastamento.pas' {FFolhaAfastamento},
  UFolhaFeriasColetivas in 'Tela\UFolhaFeriasColetivas.pas' {FFolhaFeriasColetivas},
  FolhaFeriasColetivasController in 'Controller\FolhaFeriasColetivasController.pas',
  UFeriasPeriodoAquisitivo in 'Tela\UFeriasPeriodoAquisitivo.pas' {FFeriasPeriodoAquisitivo},
  FeriasPeriodoAquisitivoController in 'Controller\FeriasPeriodoAquisitivoController.pas',
  FolhaFechamentoController in 'Controller\FolhaFechamentoController.pas',
  UFolhaFechamento in 'Tela\UFolhaFechamento.pas' {FFolhaFechamento},
  FolhaLancamentoCabecalhoController in 'Controller\FolhaLancamentoCabecalhoController.pas',
  UFolhaLancamento in 'Tela\UFolhaLancamento.pas' {FFolhaLancamento},
  ColaboradorController in '..\Comum\Controller\ColaboradorController.pas',
  FolhaHistoricoSalarialController in 'Controller\FolhaHistoricoSalarialController.pas',
  UFolhaHistoricoSalarial in 'Tela\UFolhaHistoricoSalarial.pas' {FFolhaHistoricoSalarial},
  FolhaValeTransporteController in 'Controller\FolhaValeTransporteController.pas',
  UFolhaValeTransporte in 'Tela\UFolhaValeTransporte.pas' {FFolhaValeTransporte},
  UFolhaInformativosGuias in 'Tela\UFolhaInformativosGuias.pas' {FFolhaInformativosGuias},
  FolhaRescisaoController in 'Controller\FolhaRescisaoController.pas',
  UFolhaRescisao in 'Tela\UFolhaRescisao.pas' {FFolhaRescisao},
  FolhaPppController in 'Controller\FolhaPppController.pas',
  UFolhaPpp in 'Tela\UFolhaPpp.pas' {FFolhaPpp},
  FolhaInssServicoController in 'Controller\FolhaInssServicoController.pas',
  UFolhaInssServico in 'Tela\UFolhaInssServico.pas' {FFolhaInssServico},
  UFolhaInss in 'Tela\UFolhaInss.pas' {FFolhaInss},
  FolhaInssController in 'Controller\FolhaInssController.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  OperadoraPlanoSaudeVO in '..\..\Comum\VO\OperadoraPlanoSaudeVO.pas',
  OperadoraPlanoSaudeController in 'Controller\OperadoraPlanoSaudeController.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  CargoController in 'Controller\CargoController.pas',
  EmpresaTransporteItinerarioVO in '..\..\Comum\VO\EmpresaTransporteItinerarioVO.pas',
  EmpresaTransporteItinerarioController in 'Controller\EmpresaTransporteItinerarioController.pas',
  ViewPessoaColaboradorVO in '..\..\Comum\VO\ViewPessoaColaboradorVO.pas',
  ViewPessoaColaboradorController in 'Controller\ViewPessoaColaboradorController.pas',
  UPreview in 'Tela\UPreview.pas' {FPreview};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'T2Ti ERP Folha de Pagamento';
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.CreateForm(TFFolhaInss, FFolhaInss);
  Application.CreateForm(TFPreview, FPreview);
  Application.Run;
end.
