program T2TiERPVendas;

uses
  Forms,
  Tipos in '..\Comum\Tipos.pas',
  Conversor in '..\Comum\Conversor.pas',
  NotificationService in '..\Comum\NotificationService.pas',
  SessaoUsuario in '..\Comum\SessaoUsuario.pas',
  UsuarioController in '..\Comum\Controller\UsuarioController.pas',
  Controller in '..\Comum\Controller\Controller.pas',
  FuncaoController in '..\Comum\Controller\FuncaoController.pas',
  PapelController in '..\Comum\Controller\PapelController.pas',
  PapelFuncaoController in '..\Comum\Controller\PapelFuncaoController.pas',
  UTelaCadastro in '..\Comum\Tela\UTelaCadastro.pas' {FTelaCadastro},
  UTela in '..\Comum\Tela\UTela.pas' {FTela},
  ULookup in '..\Comum\Tela\ULookup.pas' {FLookup},
  UBase in '..\Comum\Tela\UBase.pas' {FBase},
  UDataModule in '..\Comum\Tela\UDataModule.pas' {FDataModule: TDataModule},
  UFiltro in '..\Comum\Tela\UFiltro.pas' {FFiltro},
  ULogin in '..\Comum\Tela\ULogin.pas' {FLogin},
  UMenu in 'Tela\UMenu.pas' {FMenu},
  Atributos in '..\..\Comum\Atributos.pas',
  Biblioteca in '..\..\Comum\Biblioteca.pas',
  Constantes in '..\..\Comum\Constantes.pas',
  FuncaoVO in '..\..\Comum\VO\FuncaoVO.pas',
  JSonVO in '..\..\Comum\VO\JSonVO.pas',
  UsuarioVO in '..\..\Comum\VO\UsuarioVO.pas',
  PapelFuncaoVO in '..\..\Comum\VO\PapelFuncaoVO.pas',
  PapelVO in '..\..\Comum\VO\PapelVO.pas',
  UTipoNotaFiscal in 'Tela\UTipoNotaFiscal.pas' {FTipoNotaFiscal},
  TipoNotaFiscalVO in '..\..\Comum\VO\TipoNotaFiscalVO.pas',
  UCondicoesPagamento in 'Tela\UCondicoesPagamento.pas' {FCondicoesPagamento},
  UOrcamentoPedidoVenda in 'Tela\UOrcamentoPedidoVenda.pas' {FOrcamentoPedidoVenda},
  VendedorVO in '..\..\Comum\VO\VendedorVO.pas',
  UVenda in 'Tela\UVenda.pas' {FVenda},
  UFreteVenda in 'Tela\UFreteVenda.pas' {FFreteVenda},
  SetorVO in '..\..\Comum\VO\SetorVO.pas',
  EmpresaVO in '..\..\Comum\VO\EmpresaVO.pas',
  PessoaVO in '..\..\Comum\VO\PessoaVO.pas',
  EnderecoVO in '..\..\Comum\VO\EnderecoVO.pas',
  PessoaFisicaVO in '..\..\Comum\VO\PessoaFisicaVO.pas',
  PessoaJuridicaVO in '..\..\Comum\VO\PessoaJuridicaVO.pas',
  FpasVO in '..\..\Comum\VO\FpasVO.pas',
  UfVO in '..\..\Comum\VO\UfVO.pas',
  PaisVO in '..\..\Comum\VO\PaisVO.pas',
  ContatoVO in '..\..\Comum\VO\ContatoVO.pas',
  ContadorVO in '..\..\Comum\VO\ContadorVO.pas',
  SindicatoVO in '..\..\Comum\VO\SindicatoVO.pas',
  ContabilContaVO in '..\..\Comum\VO\ContabilContaVO.pas',
  CargoVO in '..\..\Comum\VO\CargoVO.pas',
  NivelFormacaoVO in '..\..\Comum\VO\NivelFormacaoVO.pas',
  TipoColaboradorVO in '..\..\Comum\VO\TipoColaboradorVO.pas',
  TransportadoraVO in '..\..\Comum\VO\TransportadoraVO.pas',
  ClienteVO in '..\..\Comum\VO\ClienteVO.pas',
  ClienteController in '..\Cadastros Base\Controller\ClienteController.pas',
  TributOperacaoFiscalVO in '..\..\Comum\VO\TributOperacaoFiscalVO.pas',
  AtividadeForCliVO in '..\..\Comum\VO\AtividadeForCliVO.pas',
  SituacaoForCliVO in '..\..\Comum\VO\SituacaoForCliVO.pas',
  TransportadoraController in '..\Cadastros Base\Controller\TransportadoraController.pas',
  ColaboradorVO in '..\..\Comum\VO\ColaboradorVO.pas',
  SituacaoColaboradorVO in '..\..\Comum\VO\SituacaoColaboradorVO.pas',
  TipoAdmissaoVO in '..\..\Comum\VO\TipoAdmissaoVO.pas',
  ViewSessaoEmpresaController in '..\Comum\Controller\ViewSessaoEmpresaController.pas',
  EmpresaController in '..\Comum\Controller\EmpresaController.pas',
  ViewSessaoEmpresaVO in '..\..\Comum\VO\ViewSessaoEmpresaVO.pas',
  AdministrativoFormularioVO in '..\..\Comum\VO\AdministrativoFormularioVO.pas',
  EmpresaSessaoVO in '..\..\Comum\VO\EmpresaSessaoVO.pas',
  ColaboradorPessoaVO in '..\..\Comum\VO\ColaboradorPessoaVO.pas',
  ClientePessoaVO in '..\..\Comum\VO\ClientePessoaVO.pas',
  FornecedorPessoaVO in '..\..\Comum\VO\FornecedorPessoaVO.pas',
  TipoNotaFiscalController in 'Controller\TipoNotaFiscalController.pas',
  TributOperacaoFiscalController in 'Controller\TributOperacaoFiscalController.pas',
  VendaCabecalhoController in 'Controller\VendaCabecalhoController.pas',
  VendaComissaoController in 'Controller\VendaComissaoController.pas',
  VendaCondicoesPagamentoController in 'Controller\VendaCondicoesPagamentoController.pas',
  VendaFreteController in 'Controller\VendaFreteController.pas',
  VendaOrcamentoCabecalhoController in 'Controller\VendaOrcamentoCabecalhoController.pas',
  VendaRomaneioEntregaController in 'Controller\VendaRomaneioEntregaController.pas',
  VendedorController in 'Controller\VendedorController.pas',
  VendaCabecalhoVO in '..\..\Comum\VO\VendaCabecalhoVO.pas',
  VendaComissaoVO in '..\..\Comum\VO\VendaComissaoVO.pas',
  VendaCondicoesPagamentoVO in '..\..\Comum\VO\VendaCondicoesPagamentoVO.pas',
  VendaCondicoesParcelasVO in '..\..\Comum\VO\VendaCondicoesParcelasVO.pas',
  VendaDetalheVO in '..\..\Comum\VO\VendaDetalheVO.pas',
  VendaFreteVO in '..\..\Comum\VO\VendaFreteVO.pas',
  VendaOrcamentoCabecalhoVO in '..\..\Comum\VO\VendaOrcamentoCabecalhoVO.pas',
  VendaOrcamentoDetalheVO in '..\..\Comum\VO\VendaOrcamentoDetalheVO.pas',
  VendaRomaneioEntregaVO in '..\..\Comum\VO\VendaRomaneioEntregaVO.pas',
  VendaCondicoesParcelasController in 'Controller\VendaCondicoesParcelasController.pas',
  ProdutoVO in '..\..\Comum\VO\ProdutoVO.pas',
  UnidadeProdutoVO in '..\..\Comum\VO\UnidadeProdutoVO.pas',
  AlmoxarifadoVO in '..\..\Comum\VO\AlmoxarifadoVO.pas',
  TributGrupoTributarioVO in '..\..\Comum\VO\TributGrupoTributarioVO.pas',
  ProdutoController in '..\Cadastros Base\Controller\ProdutoController.pas',
  PessoaFisicaJuridicaVO in '..\..\Comum\VO\PessoaFisicaJuridicaVO.pas',
  TransportadoraPessoaVO in '..\..\Comum\VO\TransportadoraPessoaVO.pas',
  VendaOrcamentoDetalheController in 'Controller\VendaOrcamentoDetalheController.pas',
  UVendaRomaneioEntrega in 'Tela\UVendaRomaneioEntrega.pas' {FVendaRomaneioEntrega},
  ColaboradorController in '..\Cadastros Base\Controller\ColaboradorController.pas',
  ProdutoSubGrupoVO in '..\..\Comum\VO\ProdutoSubGrupoVO.pas',
  ProdutoGrupoVO in '..\..\Comum\VO\ProdutoGrupoVO.pas',
  ProdutoMarcaVO in '..\..\Comum\VO\ProdutoMarcaVO.pas',
  TributIcmsCustomCabVO in '..\..\Comum\VO\TributIcmsCustomCabVO.pas',
  TributIcmsCustomDetVO in '..\..\Comum\VO\TributIcmsCustomDetVO.pas',
  CfopVO in '..\..\Comum\VO\CfopVO.pas',
  VendaDetalheController in 'Controller\VendaDetalheController.pas',
  PlanoContaRefSpedVO in '..\..\Comum\VO\PlanoContaRefSpedVO.pas',
  PlanoContaVO in '..\..\Comum\VO\PlanoContaVO.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.Run;
end.
