program T2TiERPNFCe;

uses
  FMX.Forms,
  UMenu in 'Tela\UMenu.pas' {FMenu},
  UCliente in 'Tela\UCliente.pas' {FCliente},
  UProduto in 'Tela\UProduto.pas' {FProduto},
  ControleEstoqueController in 'Controller\ControleEstoqueController.pas',
  Controller in 'Controller\Controller.pas',
  DAVController in 'Controller\DAVController.pas',
  DavDetalheController in 'Controller\DavDetalheController.pas',
  EmpresaEnderecoController in 'Controller\EmpresaEnderecoController.pas',
  FinLancamentoReceberController in 'Controller\FinLancamentoReceberController.pas',
  NfceConfiguracaoController in 'Controller\NfceConfiguracaoController.pas',
  NfceFechamentoController in 'Controller\NfceFechamentoController.pas',
  NfceMovimentoController in 'Controller\NfceMovimentoController.pas',
  NfceOperadorController in 'Controller\NfceOperadorController.pas',
  NfceSangriaController in 'Controller\NfceSangriaController.pas',
  NfceSuprimentoController in 'Controller\NfceSuprimentoController.pas',
  NfceTipoPagamentoController in 'Controller\NfceTipoPagamentoController.pas',
  NfceTurnoController in 'Controller\NfceTurnoController.pas',
  NfeConfiguracaoController in 'Controller\NfeConfiguracaoController.pas',
  NfeFormaPagamentoController in 'Controller\NfeFormaPagamentoController.pas',
  NfeNumeroController in 'Controller\NfeNumeroController.pas',
  ProdutoController in 'Controller\ProdutoController.pas',
  VendaController in 'Controller\VendaController.pas',
  VendedorController in 'Controller\VendedorController.pas',
  ViewNfceClienteController in 'Controller\ViewNfceClienteController.pas',
  Atributos in 'Util\Atributos.pas',
  Biblioteca in 'Util\Biblioteca.pas',
  Constantes in 'Util\Constantes.pas',
  Conversor in 'Util\Conversor.pas',
  SessaoUsuario in 'Util\SessaoUsuario.pas',
  T2TiORM in 'Util\T2TiORM.pas',
  Tipos in 'Util\Tipos.pas',
  CfopVO in 'VO\CfopVO.pas',
  DavCabecalhoVO in 'VO\DavCabecalhoVO.pas',
  DAVDetalheVO in 'VO\DAVDetalheVO.pas',
  EmpresaEnderecoVO in 'VO\EmpresaEnderecoVO.pas',
  EmpresaVO in 'VO\EmpresaVO.pas',
  FinLancamentoReceberVO in 'VO\FinLancamentoReceberVO.pas',
  FinParcelaReceberVO in 'VO\FinParcelaReceberVO.pas',
  FiscalNotaFiscalEntradaVO in 'VO\FiscalNotaFiscalEntradaVO.pas',
  JSonVO in 'VO\JSonVO.pas',
  NfceCaixaVO in 'VO\NfceCaixaVO.pas',
  NfceConfiguracaoBalancaVO in 'VO\NfceConfiguracaoBalancaVO.pas',
  NfceConfiguracaoLeitorSerVO in 'VO\NfceConfiguracaoLeitorSerVO.pas',
  NfceConfiguracaoVO in 'VO\NfceConfiguracaoVO.pas',
  NfceFechamentoVO in 'VO\NfceFechamentoVO.pas',
  NfceMovimentoVO in 'VO\NfceMovimentoVO.pas',
  NfceOperadorVO in 'VO\NfceOperadorVO.pas',
  NfcePosicaoComponentesVO in 'VO\NfcePosicaoComponentesVO.pas',
  NfceResolucaoVO in 'VO\NfceResolucaoVO.pas',
  NfceSangriaVO in 'VO\NfceSangriaVO.pas',
  NfceSuprimentoVO in 'VO\NfceSuprimentoVO.pas',
  NfceTipoPagamentoVO in 'VO\NfceTipoPagamentoVO.pas',
  NfceTurnoVO in 'VO\NfceTurnoVO.pas',
  NfeAcessoXmlVO in 'VO\NfeAcessoXmlVO.pas',
  NfeCabecalhoVO in 'VO\NfeCabecalhoVO.pas',
  NfeCanaDeducoesSafraVO in 'VO\NfeCanaDeducoesSafraVO.pas',
  NfeCanaFornecimentoDiarioVO in 'VO\NfeCanaFornecimentoDiarioVO.pas',
  NfeCanaVO in 'VO\NfeCanaVO.pas',
  NfeConfiguracaoVO in 'VO\NfeConfiguracaoVO.pas',
  NfeCteReferenciadoVO in 'VO\NfeCteReferenciadoVO.pas',
  NfeCupomFiscalReferenciadoVO in 'VO\NfeCupomFiscalReferenciadoVO.pas',
  NfeDeclaracaoImportacaoVO in 'VO\NfeDeclaracaoImportacaoVO.pas',
  NfeDestinatarioVO in 'VO\NfeDestinatarioVO.pas',
  NfeDetalheImpostoCofinsVO in 'VO\NfeDetalheImpostoCofinsVO.pas',
  NfeDetalheImpostoIcmsVO in 'VO\NfeDetalheImpostoIcmsVO.pas',
  NfeDetalheImpostoIiVO in 'VO\NfeDetalheImpostoIiVO.pas',
  NfeDetalheImpostoIpiVO in 'VO\NfeDetalheImpostoIpiVO.pas',
  NfeDetalheImpostoIssqnVO in 'VO\NfeDetalheImpostoIssqnVO.pas',
  NfeDetalheImpostoPisVO in 'VO\NfeDetalheImpostoPisVO.pas',
  NfeDetalheVO in 'VO\NfeDetalheVO.pas',
  NfeDetEspecificoArmamentoVO in 'VO\NfeDetEspecificoArmamentoVO.pas',
  NfeDetEspecificoCombustivelVO in 'VO\NfeDetEspecificoCombustivelVO.pas',
  NfeDetEspecificoMedicamentoVO in 'VO\NfeDetEspecificoMedicamentoVO.pas',
  NfeDetEspecificoVeiculoVO in 'VO\NfeDetEspecificoVeiculoVO.pas',
  NfeDuplicataVO in 'VO\NfeDuplicataVO.pas',
  NfeEmitenteVO in 'VO\NfeEmitenteVO.pas',
  NfeExportacaoVO in 'VO\NfeExportacaoVO.pas',
  NfeFaturaVO in 'VO\NfeFaturaVO.pas',
  NfeFormaPagamentoVO in 'VO\NfeFormaPagamentoVO.pas',
  NfeImportacaoDetalheVO in 'VO\NfeImportacaoDetalheVO.pas',
  NfeLocalEntregaVO in 'VO\NfeLocalEntregaVO.pas',
  NfeLocalRetiradaVO in 'VO\NfeLocalRetiradaVO.pas',
  NfeNfReferenciadaVO in 'VO\NfeNfReferenciadaVO.pas',
  NfeNumeroVO in 'VO\NfeNumeroVO.pas',
  NfeProcessoReferenciadoVO in 'VO\NfeProcessoReferenciadoVO.pas',
  NfeProdRuralReferenciadaVO in 'VO\NfeProdRuralReferenciadaVO.pas',
  NfeReferenciadaVO in 'VO\NfeReferenciadaVO.pas',
  NfeTransporteReboqueVO in 'VO\NfeTransporteReboqueVO.pas',
  NfeTransporteVO in 'VO\NfeTransporteVO.pas',
  NfeTransporteVolumeLacreVO in 'VO\NfeTransporteVolumeLacreVO.pas',
  NfeTransporteVolumeVO in 'VO\NfeTransporteVolumeVO.pas',
  NivelFormacaoVO in 'VO\NivelFormacaoVO.pas',
  ProdutoLoteVO in 'VO\ProdutoLoteVO.pas',
  ProdutoVO in 'VO\ProdutoVO.pas',
  TributOperacaoFiscalVO in 'VO\TributOperacaoFiscalVO.pas',
  UnidadeProdutoVO in 'VO\UnidadeProdutoVO.pas',
  VendedorVO in 'VO\VendedorVO.pas',
  ViewNfceClienteVO in 'VO\ViewNfceClienteVO.pas',
  VO in 'VO\VO.pas',
  UPagamento in 'Tela\UPagamento.pas' {FPagamento},
  UDataModuleConexao in '..\..\Comum\DataModule\UDataModuleConexao.pas' {FDataModuleConexao: TDataModule},
  UDataModule in '..\Comum\DataModule\UDataModule.pas' {FDataModule: TDataModule},
  UDanfe in 'Tela\UDanfe.pas' {FDanfe};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFMenu, FMenu);
  Application.CreateForm(TFCliente, FCliente);
  Application.CreateForm(TFProduto, FProduto);
  Application.CreateForm(TFPagamento, FPagamento);
  Application.CreateForm(TFDataModuleConexao, FDataModuleConexao);
  Application.CreateForm(TFDataModule, FDataModule);
  Application.CreateForm(TFDanfe, FDanfe);
  Application.Run;
end.
